---
abstract: 'interpolate between lazily-evaluated points'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Interpolator
provides:
  Math::Interpolator:
    file: lib/Math/Interpolator.pm
    version: 0.004
  Math::Interpolator::Knot:
    file: lib/Math/Interpolator/Knot.pm
    version: 0.004
  Math::Interpolator::Linear:
    file: lib/Math/Interpolator/Linear.pm
    version: 0.004
  Math::Interpolator::Robust:
    file: lib/Math/Interpolator/Robust.pm
    version: 0.004
  Math::Interpolator::Source:
    file: lib/Math/Interpolator/Source.pm
    version: 0.004
requires:
  Carp: 0
  integer: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
